#ifndef __EAF41_H
#define __EAF41_H

#include <string>
#include <fstream>

#include "FeindNs.h"
#include "Parent.h"

class FEIND::Eaf41
{
 public:
  Eaf41(const LibDefine& lib);
  ErrCode LoadLibrary();

 private:
  std::ifstream InFile;
  const static int NumGroups;
  Path ConvertPath(const std::string& str);
  int ParticleEtoF(const char part);
  Kza DaughterEtoF(const std::string& daughter);

  void SkipHeader();
  int FissionType(const char projectile);

  /// Add charged particle production cross-section.
  /** As I know it, the Eaf41 transmutation lib does not explicitely give
   *  cross-sections, so they must be generated by some all of the reaction
   *  products.
   */
  void AddCPPCS(Kza parent, Path& path);

  /// This function adds to the parent total cross section.
  /** The cross section stored in the second argument is added to the total
   *  cross section for the parent. If the parents cross section hasn't been
   *  created yet, this function will creat it.
   */
  void AddToCs(Kza parent, Kza daughter, std::vector<double> newCs);

  std::vector<Kza> Cpt;
};

#endif
