pair<string,int> FEIND::Elements[NUM_ELEMENTS] = 
  {
    pair<string,int>("H" , 1  ),
    pair<string,int>("He", 2  ),
    pair<string,int>("Li", 3  ),
    pair<string,int>("Be", 4  ),
    pair<string,int>("B" , 5  ),
    pair<string,int>("C" , 6  ),
    pair<string,int>("N" , 7  ),
    pair<string,int>("O" , 8  ),
    pair<string,int>("F" , 9  ),
    pair<string,int>("Ne", 10 ),
    pair<string,int>("Na", 11 ),
    pair<string,int>("Mg", 12 ),
    pair<string,int>("Al", 13 ),
    pair<string,int>("Si", 14 ),
    pair<string,int>("P" , 15 ),
    pair<string,int>("S" , 16 ),
    pair<string,int>("Cl", 17 ),
    pair<string,int>("Ar", 18 ),
    pair<string,int>("K" , 19 ),
    pair<string,int>("Ca", 20 ),
    pair<string,int>("Sc", 21 ),
    pair<string,int>("Ti", 22 ),
    pair<string,int>("V" , 23 ),
    pair<string,int>("Cr", 24 ),
    pair<string,int>("Mn", 25 ),
    pair<string,int>("Fe", 26 ),
    pair<string,int>("Co", 27 ),
    pair<string,int>("Ni", 28 ),
    pair<string,int>("Cu", 29 ),
    pair<string,int>("Zn", 30 ),
    pair<string,int>("Ga", 31 ),
    pair<string,int>("Ge", 32 ),
    pair<string,int>("As", 33 ),
    pair<string,int>("Se", 34 ),
    pair<string,int>("Br", 35 ),
    pair<string,int>("Kr", 36 ),
    pair<string,int>("Rb", 37 ),
    pair<string,int>("Sr", 38 ),
    pair<string,int>("Y" , 39 ),
    pair<string,int>("Zr", 40 ),
    pair<string,int>("Nb", 41 ),
    pair<string,int>("Mo", 42 ),
    pair<string,int>("Tc", 43 ),
    pair<string,int>("Ru", 44 ),
    pair<string,int>("Rh", 45 ),
    pair<string,int>("Pd", 46 ),
    pair<string,int>("Ag", 47 ),
    pair<string,int>("Cd", 48 ),
    pair<string,int>("In", 49 ),
    pair<string,int>("Sn", 50 ),
    pair<string,int>("Sb", 51 ),
    pair<string,int>("Te", 52 ),
    pair<string,int>("I" , 53 ),
    pair<string,int>("Xe", 54 ),
    pair<string,int>("Cs", 55 ),
    pair<string,int>("Ba", 56 ),
    pair<string,int>("La", 57 ),
    pair<string,int>("Ce", 58 ),
    pair<string,int>("Pr", 59 ),
    pair<string,int>("Nd", 60 ),
    pair<string,int>("Pm", 61 ),
    pair<string,int>("Sm", 62 ),
    pair<string,int>("Eu", 63 ),
    pair<string,int>("Gd", 64 ),
    pair<string,int>("Tb", 65 ),
    pair<string,int>("Dy", 66 ),
    pair<string,int>("Ho", 67 ),
    pair<string,int>("Er", 68 ),
    pair<string,int>("Tm", 69 ),
    pair<string,int>("Yb", 70 ),
    pair<string,int>("Lu", 71 ),
    pair<string,int>("Hf", 72 ),
    pair<string,int>("Ta", 73 ),
    pair<string,int>("W" , 74 ),
    pair<string,int>("Re", 75 ),
    pair<string,int>("Os", 76 ),
    pair<string,int>("Ir", 77 ),
    pair<string,int>("Pt", 78 ),
    pair<string,int>("Au", 79 ),
    pair<string,int>("Hg", 80 ),
    pair<string,int>("Tl", 81 ),
    pair<string,int>("Pb", 82 ),
    pair<string,int>("Bi", 83 ),
    pair<string,int>("Po", 84 ),
    pair<string,int>("At", 85 ),
    pair<string,int>("Rn", 86 ),
    pair<string,int>("Fr", 87 ),
    pair<string,int>("Ra", 88 ),
    pair<string,int>("Ac", 89 ),
    pair<string,int>("Th", 90 ),
    pair<string,int>("Pa", 91 ),
    pair<string,int>("U" , 92 ),
    pair<string,int>("Np", 93 ),
    pair<string,int>("Pu", 94 ),
    pair<string,int>("Am", 95 ),
    pair<string,int>("Cm", 96 ),
    pair<string,int>("Bk", 97 ),
    pair<string,int>("Cf", 98 ),
    pair<string,int>("Es", 99 ),
    pair<string,int>("Fm", 100),
    pair<string,int>("Md", 101),
    pair<string,int>("No", 102),
    pair<string,int>("Lr", 103),
    pair<string,int>("Rf", 104),
    pair<string,int>("Ha", 105),
    pair<string,int>("Sg", 106),
    pair<string,int>("Ns", 107),
    pair<string,int>("Hs", 108),
    pair<string,int>("Mt", 109),
    pair<string,int>("Ds", 110)
  };

int FEIND::GetAtomicNumber(const std::string& symbol)
{
  // We will travers the Elements array, until we find the symol:
  for(int i = 0; i < NUM_ELEMENTS; i++)
    {
      if(Elements[i].first == symbol)
	return i+1;	
    }
}
     
  
const string FEIND::GetAtomicSymbol(int atomicNumber)  
{
  return Elements[atomicNumber-1].first;
}
